### ISSUE TITLE
feat: allow modifying margin of the UI elements

### ISSUE THREAD

**Issue by natterstefan** [sLeeNguyen/react-flip-clock-countdown#10]
Hi @sLeeNguyen.

First of all, thanks for creating this component. I want to propose a new feature that allows modifying the `margin` values of the colons. They are too broad in my use case, and I need help modifying them.

https://github.com/sLeeNguyen/react-flip-clock-countdown/blob/7c281901cf447d72f67df2d871e95067c8fbb5d2/src/styles.module.css#L132-L133

I wonder if `--fcc-separator-margin` would fit.

**Comment by natterstefan** [comment]
Follow-Up Question:

How can I modify the space between the numbers as well? They are too broad for us too:

<img width="157" alt="image" src="https://user-images.githubusercontent.com/1043668/229514018-46266a41-f459-4e24-b3d7-e0761c832117.png">

**Comment by sLeeNguyen** [comment]
Thanks for your suggestions.

I'm considering adding a specific `classname` (or `style`) for each UI element so that we will have highest customizability. What do you think? @natterstefan

**Comment by natterstefan** [comment]
Hi @sLeeNguyen.

That'd be great. I think it'd be great if you only ensure the values are horizontally aligned (e.g., with `flex`) but leave as much customizability to the users of the component.

Or you expose all settings via a `theme`-like object and let users decide how to use and overwrite it (globally or per usage).

**Comment by a11rew** [comment]
+1 on this. The space between blocks in particular is a headache.
