### ISSUE TITLE
Bug: Safari has issues when rendering multiple FlipClockCountdowns

### ISSUE THREAD

**Issue by natterstefan** [sLeeNguyen/react-flip-clock-countdown#11]
Hi @sLeeNguyen,

I have several strange glitches on Safari, including: Safari can't handle multiple instances with the same countdown

Codesandbox: https://codesandbox.io/s/react-flip-clock-countdown-example-hnkbdb?file=/src/App.js
Video: https://d.pr/v/1DW098/RCv4ldHiU4

**Comment by sLeeNguyen** [comment]
Hi @natterstefan ,

I've also had the same problem before. I don't know why. When inspecting the HTML code (inspect elements), I see that the content of the HTML tags is still updated correctly, while the display has problems. After updating safari to the latest version, I no longer see this error.

**Comment by natterstefan** [comment]
Hi @sLeeNguyen,

as you can see in the image the issue is still present in Safari 15.5.0 Which version do you use?

**Comment by sLeeNguyen** [comment]
<img width="280" alt="image" src="https://user-images.githubusercontent.com/54298446/229716737-25f98b65-421f-4b34-92eb-bc4c88695fc2.png">
I'm using 15.6 and it works well

**Comment by natterstefan** [comment]
> After updating safari to the latest version, I no longer see this error.

But that does not mean it's fixed for others as well as it unfortunately seems. The video I've attached shows it is still buggy. Do you think it is related to the #12 bug? I need to verify if the bug disappears if I only have one countdown on the page.

**Comment by sLeeNguyen** [comment]
> Do you think it is related to the https://github.com/sLeeNguyen/react-flip-clock-countdown/issues/12 bug?

I don't think so. As I said I've checked the content of the HTML tags and it's still updated correctly, just the display has problems. I've tested in Safari v14 and it works well.
