### ISSUE TITLE
Bug: Safari glitch when using CSS perspective

### ISSUE THREAD

**Issue by natterstefan** [sLeeNguyen/react-flip-clock-countdown#12]
Hi @sLeeNguyen,

I wonder why `perspective` is required and if one can disable it and make it optional.

https://github.com/sLeeNguyen/react-flip-clock-countdown/blob/7c281901cf447d72f67df2d871e95067c8fbb5d2/src/styles.module.css#L57

Because in our setup, Safari has issues when using this value:

![image](https://user-images.githubusercontent.com/1043668/229557994-8f9f714c-d997-4e05-88fb-df4492406838.png)

I started using `patch-package` to fix this (and #10), but it seems this is either a bug or should be configurable. What do you think?

**Comment by sLeeNguyen** [comment]
I use it to get 3D transition each time the clock flip

**Comment by natterstefan** [comment]
To me it looks like it also works without it, is there a huge difference when not using it?

**Comment by sLeeNguyen** [comment]
https://user-images.githubusercontent.com/54298446/229718571-64f1be81-1862-410f-a615-fa93f4718dd5.mov

You can see in this video the difference. As the project description "A 3D animated countdown component for React", I want to make it 3D animated. In your case, seem like you just want to display the normal clock (without animation)

**Comment by sLeeNguyen** [comment]
I'm quite busy at the moment and I don't know when this feature will be released. If you can, don't hesitate to create a PR.

**Comment by natterstefan** [comment]
Hey @sLeeNguyen,

from what I've seen so far in our environment the problem was gone once I added `overflow: hidden` to the same class using `perspective`. I am not sure how to proof it as I cannot share more insights from our project publicly.
