### ISSUE TITLE
Feature: Allow modify border radius of digitBlock

### ISSUE THREAD

**Issue by didix16** [sLeeNguyen/react-flip-clock-countdown#16]
Hi! Thanks for this amazing component. I wonder if you could add some new CSS vars to customize the digit blocks border radius (top and bottom).
I have many webs, which different styles and I want to customize in some of them to be squared, not rounded.

Regarding to #10, you can make all UI elements full customizable so it could be integrated with specific themes in any website. I think it could be cool and give much power to the component.

What do you think @sLeeNguyen ?

**Comment by sLeeNguyen** [comment]
Hello. We have some properties that allow you to customize the component's styles like: `digitBlockStyle`, `labelStyle`, ... Have you tried them?

**Comment by sLeeNguyen** [comment]
btw I will try to update the component to make it more customizable. Thank you for your suggestion.

**Comment by didix16** [comment]
> Hello. We have some properties that allow you to customize the component's styles like: `digitBlockStyle`, `labelStyle`, ... Have you tried them?

Yeah I tried but I cannot change the border radius for example with that options. As I see in here
https://github.com/sLeeNguyen/react-flip-clock-countdown/blob/00fb2503100f184cfa44159780bc4f86cf3a8142/src/styles.module.css#L76-L88

And here

https://github.com/sLeeNguyen/react-flip-clock-countdown/blob/00fb2503100f184cfa44159780bc4f86cf3a8142/src/styles.module.css#L117-L129

border properties are hardcoded to 4px. It would be nice if we can override those properties too or maybe make the whole component more customizable.



> btw I will try to update the component to make it more customizable. Thank you for your suggestion.

Thank you so much !

**Comment by sLeeNguyen** [comment]
I've just add [new commit](https://github.com/sLeeNguyen/react-flip-clock-countdown/commit/54e809f2291e4931fa995bf86d203dadeac0e61f) to fix this issue. Could you try the latest version?

**Comment by didix16** [comment]
Hey @sLeeNguyen I try it with borderRadius: 0 and it looks good. Thanks!

![imagen](https://github.com/sLeeNguyen/react-flip-clock-countdown/assets/10291092/107574c1-1c7d-438d-845e-aabca524372d)
