### ISSUE TITLE
Problem: React Flip Clock is not updating correctly in inactive tab

### ISSUE THREAD

**Issue by Kostanios** [sLeeNguyen/react-flip-clock-countdown#17]
The component gets derailed if you switch to another tab, the problem is solved if you perform force render after visibilitychange event. But it would be cool to add something like this out of the box

**Comment by sLeeNguyen** [comment]
could you provide a code example?

**Comment by Kostanios** [comment]
> could you provide a code example?

Looks not perfect, but with force render timer works better due browser tabs switch:

import { useEffect, useState } from "react";
import FlipClockCountdown from "@leenguyen/react-flip-clock-countdown";

export default function CustomFlipClockCountdown({ className, onComplete, to, labels }) {
    const [_, forceRender] = useState({});

    useEffect(() => {
        const forceUpdate = () => forceRender({});
        document.addEventListener("visibilitychange", forceUpdate);

        return () => document.removeEventListener("visibilitychange", forceUpdate);
    }, []);

    return <FlipClockCountdown key={_} className={className} onComplete={onComplete} to={to} labels={labels} />;
}

**Comment by sLeeNguyen** [comment]
@Kostanios 
Sorry. I mean the code to reproduce this issue

**Comment by sLeeNguyen** [comment]
Ah. No worries. I've just understood your issue
