### ISSUE TITLE
Current time getting calculated incorrectly

### ISSUE THREAD

**Issue by srijan-mda** [sLeeNguyen/react-flip-clock-countdown#19]
I am using the flip clock in my project and found a scenario where if the user manually changes the date and time on their system, the timer gets updated as per the system's date and time.

**Comment by sLeeNguyen** [comment]
> I am using the flip clock in my project and found a scenario where if the user manually changes the date and time on their system, the timer gets updated as per the system's date and time.

I don't think it's an issue. Changing the date and time on your system should also change the countdown.

**Comment by srijan-mda** [comment]
> > I am using the flip clock in my project and found a scenario where if the user manually changes the date and time on their system, the timer gets updated as per the system's date and time.
> 
> I don't think it's an issue. Changing the date and time on your system should also change the countdown.

I want to avoid that, this way the user can avoid waiting for launch date.

**Comment by sLeeNguyen** [comment]
@srijan-mda We can't. The countdown works based on the user's system time (`timestamp`). This issue comes from the client side because their system time is wrong, they have to change it to correct time.
