### ISSUE TITLE
hide day 

### ISSUE THREAD

**Issue by Alvazz** [sLeeNguyen/react-flip-clock-countdown#6]
how to set hide day. thanks!

**Comment by sLeeNguyen** [comment]
Hi. At the moment, we have no option for this

**Comment by Alvazz** [comment]
Can you update it? After all, it shows 0 days, which is meaningless.

**Comment by sLeeNguyen** [comment]
@Alvazz I've added this feature in [v1.4.0](https://github.com/sLeeNguyen/react-flip-clock-countdown/releases/tag/v1.4.0). Please check
Here is an [example](https://github.com/sLeeNguyen/react-flip-clock-countdown#custom-section-to-be-rendered).

**Comment by Alvazz** [comment]
I will try it, thank you very much!
