### ISSUE TITLE
className in typescript

### ISSUE THREAD

**Issue by Kublick** [sLeeNguyen/react-flip-clock-countdown#7]
Seems className property its not defined, thus giving an error when used on the function.

Type '{ className: string; to: Date; digitBlockStyle: { fontSize: number; fontFamily: string; }; showLabels: false; showSeparators: true; }' is not assignable to type 'IntrinsicAttributes & Pick<FlipClockCountdownProps, "to" | "containerProps" | "labelStyle" | "digitBlockStyle" | "separatorStyle" | "dividerStyle" | "duration"> & InexactPartial<...> & InexactPartial<...>'.
  Property 'className' does not exist on type 'IntrinsicAttributes & Pick<FlipClockCountdownProps, "to" | "containerProps" | "labelStyle" | "digitBlockStyle" | "separatorStyle" | "dividerStyle" | "duration"> & InexactPartial<...> & InexactPartial<...>'.

Adding the prop to FlipClockCountdown would fix the issue

**Comment by sLeeNguyen** [comment]
@Kublick `FlipClockCountdownProps` extends properties from `React.DetailedHTMLProps<React.HTMLAttributes<HTMLDivElement>, HTMLDivElement>` so that the `className` prop should have in `FlipClockCountdown`. I think the problem might come from your react version, it should be >= 16.13.0

**Comment by Kublick** [comment]
Hello

I’m using react 18

**Comment by sLeeNguyen** [comment]
Can you show me the code you are using FlipClockCountdown and get that error?

**Comment by Kublick** [comment]
Here is a sandbox

https://stackblitz.com/edit/react-ts-egkyb6?file=Countdown.tsx

**Comment by sLeeNguyen** [comment]
The problem comes from typescript compiler, try to add this to your `tsconfig.json`
```
"compilerOptions": {
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true
  }
```
Ref: https://stackoverflow.com/questions/60551025/how-can-i-get-rid-of-my-types-react-index-can-only-be-default-imported-using
