### ISSUE TITLE
Default value for clock

### ISSUE THREAD

**Issue by derikle** [sLeeNguyen/react-flip-clock-countdown#8]
Hi, I want to set a default value for clock before its start running, maybe 00:00:00. Can this version support it. 
Thanks!

**Comment by sLeeNguyen** [comment]
The library does not have this option. You want to trigger the countdown manually, right?

**Comment by derikle** [comment]
Yes, @sLeeNguyen

**Comment by sLeeNguyen** [comment]
Got it. I'm thinking to add a new option that allows the Clock counts down for a period of time instead of just counting down to a certain time.

**Comment by derikle** [comment]
Great. Thanks @sLeeNguyen

**Comment by sLeeNguyen** [comment]
It should be in the new version. I'll try to update it when I have time
