### ISSUE TITLE
Allows countdown for a period of time

### ISSUE THREAD

**Issue by sLeeNguyen** [sLeeNguyen/react-flip-clock-countdown#9]
In the previous versions (1.4.0 and earlier), the clock has only one option is countdown to a certain time in the future and we cannot trigger the countdown clock manually.

This feature will add a new option that allows:
- countdown for a period of time
- trigger the countdown manually

**Comment by flemking** [comment]
Hello @sLeeNguyen, I hope everything is going smoothly on this issue.
I'm trying to achieve the same thing on my end.
Let me know if it will be out soon or if I can help.
Thanks! ✌🏾
